export { BookingsView } from './BookingsView';
export { ClinicalRecordsView } from './ClinicalRecordsView';
export { HiringView } from './HiringView';
export { InsightsView } from './InsightsView';
export { PatientsView } from './PatientsView';
export { ProvidersView } from './ProvidersView';
export { SalaryView } from './SalaryView';
export { TodayOpsView } from './TodayOpsView';
export { UnknownModuleView } from './shared';
