import {
  Activity,
  BriefcaseBusiness,
  CalendarDays,
  ClipboardList,
  HeartPulse,
  IndianRupee,
  LayoutDashboard,
  LineChart,
  Stethoscope,
  Users,
} from 'lucide-react';
import type {
  AdminModule,
  AdminModuleConfig,
  BookingRecord,
  ClinicalRecord,
  CompensationRecord,
  HiringCandidate,
  InsightMetric,
  PatientRecord,
  ProviderRecord,
  QueueItem,
  SlotRecord,
} from './types';

export const adminModules: AdminModuleConfig[] = [
  {
    id: 'today',
    label: "Today's Ops",
    helper: 'Daily command center',
    path: '/dashboard/admin',
    icon: LayoutDashboard,
  },
  {
    id: 'patients',
    label: 'Patients',
    helper: 'Profiles and care status',
    path: '/dashboard/admin/patients',
    icon: Users,
  },
  {
    id: 'providers',
    label: 'Providers',
    helper: 'Roster and capacity',
    path: '/dashboard/admin/providers',
    icon: Stethoscope,
  },
  {
    id: 'bookings',
    label: 'Bookings & Slots',
    helper: 'Sessions and availability',
    path: '/dashboard/admin/bookings',
    icon: CalendarDays,
  },
  {
    id: 'hiring',
    label: 'Hiring',
    helper: 'Candidate pipeline',
    path: '/dashboard/admin/hiring',
    icon: BriefcaseBusiness,
  },
  {
    id: 'salary',
    label: 'Salary',
    helper: 'Compensation approvals',
    path: '/dashboard/admin/salary',
    icon: IndianRupee,
  },
  {
    id: 'insights',
    label: 'Insights',
    helper: 'Growth and care health',
    path: '/dashboard/admin/insights',
    icon: LineChart,
  },
  {
    id: 'clinical-records',
    label: 'Clinical Records',
    helper: 'Detailed care history',
    path: '/dashboard/admin/clinical-records',
    icon: HeartPulse,
  },
];

export const adminModuleIds = adminModules.map((module) => module.id);

export function isAdminModule(value: string | undefined): value is AdminModule {
  return adminModuleIds.includes(value as AdminModule);
}

export const insightMetrics: InsightMetric[] = [
  {
    id: 'sessions-today',
    label: 'Sessions today',
    value: '28',
    delta: '+12%',
    helper: '9 completed, 16 scheduled, 3 pending confirmation',
    tone: 'sage',
  },
  {
    id: 'provider-utilization',
    label: 'Provider utilization',
    value: '82%',
    delta: '+6%',
    helper: 'Across active therapists this week',
    tone: 'blue',
  },
  {
    id: 'care-followups',
    label: 'Care follow-ups',
    value: '11',
    delta: '4 urgent',
    helper: 'Requires admin or provider response',
    tone: 'rose',
  },
  {
    id: 'pending-payouts',
    label: 'Pending payouts',
    value: 'Rs. 1.82L',
    delta: '6 approvals',
    helper: 'Hybrid salary and session incentives',
    tone: 'amber',
  },
];

export const opsQueues: QueueItem[] = [
  {
    id: 'risk-followup',
    title: 'High-risk patient follow-up',
    meta: 'Aarav Sharma needs same-day clinical review',
    status: 'Urgent',
    tone: 'red',
  },
  {
    id: 'slot-gap',
    title: 'Evening slot shortage',
    meta: 'Only 2 open slots after 6 PM this week',
    status: 'Capacity',
    tone: 'amber',
  },
  {
    id: 'interview',
    title: 'Provider interview pending',
    meta: 'Dr. Nisha Patel credential check complete',
    status: 'Hiring',
    tone: 'blue',
  },
  {
    id: 'payroll',
    title: 'Payroll approval batch',
    meta: '6 provider payouts awaiting review',
    status: 'Salary',
    tone: 'rose',
  },
];

export const patients: PatientRecord[] = [
  {
    id: 'pat-001',
    name: 'Aarav Sharma',
    age: 29,
    status: 'Active care',
    tone: 'red',
    assignedProvider: 'Dr. Kavya Rao',
    nextSession: 'Today, 5:00 PM',
    paymentStatus: 'Package active',
    intakeStatus: 'Complete',
    riskLevel: 'High',
    concern: 'Anxiety, sleep disruption',
    sessionsCompleted: 8,
    lastContact: 'Today, 11:20 AM',
    clinicalRecordId: 'clin-001',
    bookingHistory: [
      { date: 'May 2', provider: 'Dr. Kavya Rao', status: 'Completed', payment: 'Included in package' },
      { date: 'May 5', provider: 'Dr. Kavya Rao', status: 'Rescheduled', payment: 'No charge' },
      { date: 'May 7', provider: 'Dr. Kavya Rao', status: 'Scheduled', payment: 'Included in package' },
    ],
  },
  {
    id: 'pat-002',
    name: 'Meera Iyer',
    age: 34,
    status: 'New intake',
    tone: 'blue',
    assignedProvider: 'Mrs. Provider-2',
    nextSession: 'Tomorrow, 11:00 AM',
    paymentStatus: 'Awaiting payment',
    intakeStatus: 'Needs review',
    riskLevel: 'Moderate',
    concern: 'Burnout, relationship stress',
    sessionsCompleted: 1,
    lastContact: 'Yesterday, 6:10 PM',
    clinicalRecordId: 'clin-002',
    bookingHistory: [
      { date: 'May 4', provider: 'Mrs. Provider-2', status: 'Completed', payment: 'Paid' },
      { date: 'May 8', provider: 'Mrs. Provider-2', status: 'Scheduled', payment: 'Pending' },
    ],
  },
  {
    id: 'pat-003',
    name: 'Rohan Mehta',
    age: 41,
    status: 'Steady care',
    tone: 'sage',
    assignedProvider: 'Mr. Therapist-1',
    nextSession: 'May 9, 7:00 PM',
    paymentStatus: 'Paid',
    intakeStatus: 'Complete',
    riskLevel: 'Low',
    concern: 'Motivation, mood steadiness',
    sessionsCompleted: 12,
    lastContact: 'May 6, 9:45 AM',
    clinicalRecordId: 'clin-003',
    bookingHistory: [
      { date: 'Apr 28', provider: 'Mr. Therapist-1', status: 'Completed', payment: 'Paid' },
      { date: 'May 9', provider: 'Mr. Therapist-1', status: 'Scheduled', payment: 'Paid' },
    ],
  },
  {
    id: 'pat-004',
    name: 'Sara Khan',
    age: 26,
    status: 'Follow-up due',
    tone: 'amber',
    assignedProvider: 'Dr. Provider-1',
    nextSession: 'Not booked',
    paymentStatus: 'Refund requested',
    intakeStatus: 'Complete',
    riskLevel: 'Moderate',
    concern: 'Panic episodes, sleep',
    sessionsCompleted: 3,
    lastContact: 'May 3, 2:15 PM',
    clinicalRecordId: 'clin-004',
    bookingHistory: [
      { date: 'Apr 26', provider: 'Dr. Provider-1', status: 'Completed', payment: 'Paid' },
      { date: 'May 3', provider: 'Dr. Provider-1', status: 'Cancelled', payment: 'Refund requested' },
    ],
  },
];

export const providers: ProviderRecord[] = [
  {
    id: 'prov-001',
    name: 'Dr. Kavya Rao',
    role: 'Clinical Psychologist',
    status: 'Available today',
    tone: 'sage',
    specialities: ['Anxiety', 'Sleep', 'Mindfulness'],
    load: 86,
    nextOpenSlot: 'Today, 7:30 PM',
    sessionsThisMonth: 46,
    rating: 4.8,
    salaryBand: 'Hybrid Plus',
    utilization: 88,
  },
  {
    id: 'prov-002',
    name: 'Mrs. Provider-2',
    role: 'Holistic Therapist',
    status: 'Almost full',
    tone: 'amber',
    specialities: ['Relationships', 'Habits', 'Burnout'],
    load: 94,
    nextOpenSlot: 'May 10, 4:00 PM',
    sessionsThisMonth: 39,
    rating: 4.6,
    salaryBand: 'Hybrid Standard',
    utilization: 91,
  },
  {
    id: 'prov-003',
    name: 'Mr. Therapist-1',
    role: 'CBT Therapist',
    status: 'Open capacity',
    tone: 'blue',
    specialities: ['Motivation', 'Mood', 'CBT'],
    load: 62,
    nextOpenSlot: 'Tomorrow, 6:00 PM',
    sessionsThisMonth: 31,
    rating: 4.5,
    salaryBand: 'Session Linked',
    utilization: 67,
  },
  {
    id: 'prov-004',
    name: 'Dr. Provider-1',
    role: 'Therapist',
    status: 'Needs schedule review',
    tone: 'rose',
    specialities: ['Stress', 'Sleep', 'Anxiety'],
    load: 78,
    nextOpenSlot: 'May 11, 12:30 PM',
    sessionsThisMonth: 35,
    rating: 4.4,
    salaryBand: 'Hybrid Standard',
    utilization: 76,
  },
];

export const bookings: BookingRecord[] = [
  {
    id: 'book-001',
    patientName: 'Aarav Sharma',
    providerName: 'Dr. Kavya Rao',
    date: 'May 7',
    time: '5:00 PM',
    status: 'Needs confirmation',
    tone: 'red',
    type: 'Video',
    payment: 'Package active',
    reschedules: 1,
  },
  {
    id: 'book-002',
    patientName: 'Meera Iyer',
    providerName: 'Mrs. Provider-2',
    date: 'May 8',
    time: '11:00 AM',
    status: 'Payment pending',
    tone: 'amber',
    type: 'Video',
    payment: 'Pending',
    reschedules: 0,
  },
  {
    id: 'book-003',
    patientName: 'Rohan Mehta',
    providerName: 'Mr. Therapist-1',
    date: 'May 9',
    time: '7:00 PM',
    status: 'Confirmed',
    tone: 'sage',
    type: 'Video',
    payment: 'Paid',
    reschedules: 0,
  },
  {
    id: 'book-004',
    patientName: 'Sara Khan',
    providerName: 'Dr. Provider-1',
    date: 'May 10',
    time: '4:30 PM',
    status: 'Reschedule requested',
    tone: 'rose',
    type: 'Video',
    payment: 'Refund requested',
    reschedules: 2,
  },
];

export const slots: SlotRecord[] = [
  { id: 'slot-001', providerName: 'Dr. Kavya Rao', day: 'Today', open: 2, booked: 7, blocked: 1 },
  { id: 'slot-002', providerName: 'Mrs. Provider-2', day: 'Today', open: 1, booked: 8, blocked: 0 },
  { id: 'slot-003', providerName: 'Mr. Therapist-1', day: 'Tomorrow', open: 5, booked: 4, blocked: 1 },
  { id: 'slot-004', providerName: 'Dr. Provider-1', day: 'Tomorrow', open: 3, booked: 6, blocked: 2 },
];

export const hiringCandidates: HiringCandidate[] = [
  {
    id: 'hire-001',
    name: 'Dr. Nisha Patel',
    role: 'Clinical Psychologist',
    stage: 'Credential review',
    tone: 'blue',
    score: 92,
    credentialStatus: 'Verified',
    nextStep: 'Panel interview',
  },
  {
    id: 'hire-002',
    name: 'Aditi Menon',
    role: 'Expressive Arts Therapist',
    stage: 'Interview',
    tone: 'sage',
    score: 86,
    credentialStatus: 'Pending references',
    nextStep: 'Founder conversation',
  },
  {
    id: 'hire-003',
    name: 'Kabir Sethi',
    role: 'Counsellor',
    stage: 'Application screen',
    tone: 'amber',
    score: 74,
    credentialStatus: 'Needs review',
    nextStep: 'Portfolio review',
  },
  {
    id: 'hire-004',
    name: 'Ritika Shah',
    role: 'Therapist',
    stage: 'Offer',
    tone: 'rose',
    score: 89,
    credentialStatus: 'Verified',
    nextStep: 'Compensation approval',
  },
];

export const compensationRecords: CompensationRecord[] = [
  {
    id: 'pay-001',
    providerName: 'Dr. Kavya Rao',
    fixedSalary: 68000,
    completedSessions: 46,
    incentive: 18400,
    deductions: 0,
    netPayout: 86400,
    status: 'Ready for approval',
    tone: 'sage',
  },
  {
    id: 'pay-002',
    providerName: 'Mrs. Provider-2',
    fixedSalary: 62000,
    completedSessions: 39,
    incentive: 13200,
    deductions: 1800,
    netPayout: 73400,
    status: 'Review deductions',
    tone: 'amber',
  },
  {
    id: 'pay-003',
    providerName: 'Mr. Therapist-1',
    fixedSalary: 42000,
    completedSessions: 31,
    incentive: 15500,
    deductions: 0,
    netPayout: 57500,
    status: 'Approved',
    tone: 'blue',
  },
  {
    id: 'pay-004',
    providerName: 'Dr. Provider-1',
    fixedSalary: 56000,
    completedSessions: 35,
    incentive: 10500,
    deductions: 2500,
    netPayout: 64000,
    status: 'Needs approval',
    tone: 'rose',
  },
];

export const clinicalRecords: ClinicalRecord[] = [
  {
    id: 'clin-001',
    patientId: 'pat-001',
    patientName: 'Aarav Sharma',
    riskLevel: 'High',
    tone: 'red',
    intakeSummary: 'Sleep disruption, anxiety spikes, and recent work-related distress. Safety check required today.',
    carePlan: 'Weekly CBT-informed therapy, grounding protocol, provider follow-up after two missed check-ins.',
    medicationNotes: 'No medication records stored in Manobhav. Referred to psychiatrist if symptoms escalate.',
    lastUpdated: 'Today, 12:05 PM',
    sessionNotes: [
      {
        date: 'May 2',
        provider: 'Dr. Kavya Rao',
        note: 'Patient reported lower sleep quality but used breathing routine twice. Continue structured check-ins.',
      },
      {
        date: 'May 5',
        provider: 'Dr. Kavya Rao',
        note: 'Session rescheduled. Admin asked to confirm support call because risk score increased.',
      },
    ],
  },
  {
    id: 'clin-002',
    patientId: 'pat-002',
    patientName: 'Meera Iyer',
    riskLevel: 'Moderate',
    tone: 'blue',
    intakeSummary: 'Burnout, relationship stress, and difficulty sustaining routines after work hours.',
    carePlan: 'Short-term therapy with habit coaching, reflective prompts, and fortnightly progress review.',
    medicationNotes: 'No active medication note.',
    lastUpdated: 'Yesterday, 7:00 PM',
    sessionNotes: [
      {
        date: 'May 4',
        provider: 'Mrs. Provider-2',
        note: 'Initial session completed. Patient prefers structured exercises and evening availability.',
      },
    ],
  },
  {
    id: 'clin-003',
    patientId: 'pat-003',
    patientName: 'Rohan Mehta',
    riskLevel: 'Low',
    tone: 'sage',
    intakeSummary: 'Mood steadiness and motivation support. Strong adherence to between-session tasks.',
    carePlan: 'Maintain CBT exercises and monthly review after the next three completed sessions.',
    medicationNotes: 'No active medication note.',
    lastUpdated: 'May 6, 10:10 AM',
    sessionNotes: [
      {
        date: 'Apr 28',
        provider: 'Mr. Therapist-1',
        note: 'Mood tracking improved. Next session should review routine consistency and work boundaries.',
      },
    ],
  },
  {
    id: 'clin-004',
    patientId: 'pat-004',
    patientName: 'Sara Khan',
    riskLevel: 'Moderate',
    tone: 'amber',
    intakeSummary: 'Panic episodes and sleep difficulty. Patient requested pause after cancellation.',
    carePlan: 'Admin follow-up to rebook or close refund path. Provider suggests check-in before care pause.',
    medicationNotes: 'External psychiatrist mentioned by patient; no documents uploaded.',
    lastUpdated: 'May 3, 3:30 PM',
    sessionNotes: [
      {
        date: 'Apr 26',
        provider: 'Dr. Provider-1',
        note: 'Patient responded well to grounding routine. Follow-up recommended within one week.',
      },
    ],
  },
];

export const quickActions: QueueItem[] = [
  {
    id: 'assign-provider',
    title: 'Assign provider',
    meta: 'Match new intake with open clinical capacity',
    status: 'Patients',
    tone: 'sage',
  },
  {
    id: 'open-slots',
    title: 'Open evening slots',
    meta: 'Review provider calendar gaps for this week',
    status: 'Bookings',
    tone: 'blue',
  },
  {
    id: 'approve-payout',
    title: 'Approve payout',
    meta: 'Validate hybrid salary adjustments',
    status: 'Salary',
    tone: 'rose',
  },
  {
    id: 'review-record',
    title: 'Review clinical record',
    meta: 'Open high-risk patient history',
    status: 'Clinical',
    tone: 'red',
  },
];

export const careSignals = [
  { label: 'Completed sessions', value: 72, icon: Activity },
  { label: 'On-time follow-ups', value: 84, icon: ClipboardList },
  { label: 'Provider load balance', value: 76, icon: Users },
];
