export interface FocusAreaCategory {
  key: string;
  label: string;
  options: string[];
}

export const focusAreasTaxonomy: FocusAreaCategory[] = [
  {
    key: 'emotional-and-mood-concerns',
    label: 'Emotional & Mood Concerns',
    options: [
      'Anxiety',
      'Generalized Anxiety',
      'Panic Attacks / Panic Disorder',
      'Social Anxiety',
      'Health Anxiety',
      'Depression',
      'Persistent Low Mood',
      'Mood Swings',
      'Emotional Dysregulation',
      'Irritability',
      'Loneliness',
      'Emotional Numbness',
      'Stress Management',
      'Burnout',
      'Perfectionism',
      'Overthinking',
      'Guilt & Shame',
      'Self-Criticism',
      'Low Motivation',
    ],
  },
  {
    key: 'trauma-and-healing',
    label: 'Trauma & Healing',
    options: [
      'Trauma Recovery',
      'Childhood Trauma',
      'Complex Trauma',
      'PTSD',
      'Emotional Abuse Recovery',
      'Grief & Loss',
      'Life After Breakups',
      'Family Conflict',
      'Inner Child Work',
      'Attachment Concerns',
    ],
  },
  {
    key: 'relationships-and-interpersonal',
    label: 'Relationships & Interpersonal',
    options: [
      'Relationship Difficulties',
      'Communication Issues',
      'Couples Counselling',
      'Conflict Resolution',
      'Trust Issues',
      'Dating & Attachment Patterns',
      'Boundaries',
      'Codependency',
      'Separation / Divorce Support',
      'Friendship Issues',
      'Family Relationships',
      'Premarital Counselling',
    ],
  },
  {
    key: 'self-and-identity',
    label: 'Self & Identity',
    options: [
      'Self-Esteem',
      'Confidence Building',
      'Self-Worth',
      'Identity Exploration',
      'Personal Growth',
      'Life Transitions',
      'Decision-Making Difficulties',
      'Meaning & Purpose',
      'Values Exploration',
      'Assertiveness',
    ],
  },
  {
    key: 'cognitive-and-behavioural-concerns',
    label: 'Cognitive & Behavioural Concerns',
    options: [
      'Obsessive Thoughts',
      'OCD',
      'Intrusive Thoughts',
      'Compulsive Behaviours',
      'Rumination',
      'Emotional Avoidance',
      'Habit Change',
      'Anger Management',
      'Impulsivity',
      'Procrastination',
    ],
  },
  {
    key: 'work-/-academic-/-performance',
    label: 'Work / Academic / Performance',
    options: [
      'Academic Stress',
      'Student Mental Health',
      'Career Confusion',
      'Workplace Stress',
      'Professional Burnout',
      'Performance Anxiety',
      'Work–Life Balance',
      'Leadership Stress',
      'Productivity Challenges',
    ],
  },
  {
    key: 'body,-lifestyle-and-wellbeing',
    label: 'Body, Lifestyle & Wellbeing',
    options: [
      'Sleep Difficulties',
      'Insomnia',
      'Body Image Concerns',
      'Emotional Eating',
      'Lifestyle Change Support',
      'Mind–Body Connection',
      'Nervous System Regulation',
      'Behaviour Change',
    ],
  },
  {
    key: 'women’s-mental-health',
    label: 'Women’s Mental Health',
    options: [
      'Women’s Emotional Wellbeing',
      'Fertility & Reproductive Mental Health',
      'Pregnancy & Postpartum Adjustment',
      'Hormonal Changes',
      'Caregiver Stress',
    ],
  },
  {
    key: 'young-adult-and-adult-concerns',
    label: 'Young Adult & Adult Concerns',
    options: [
      'Quarter-Life Crisis',
      'Adulting Challenges',
      'Independence & Adjustment',
      'Relocation Stress',
      'Social Pressure',
    ],
  },
  {
    key: 'neurodiversity-informed-support-(only-if-trained)',
    label: 'Neurodiversity-Informed Support (only if trained)',
    options: [
      'ADHD Support',
      'Autism-Affirming Support',
      'Executive Function Challenges',
      'Sensory Regulation',
    ],
  },
];
